version: '3'
services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebserver
    ports:
      - "80:80"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  flask_app:
    build:
      context: ./flask_app
    container_name: flask_app
    ports:
      - "5000:80"  # Map port 5000 on the host to port 80 on the container
    volumes:
      - ./flask_app:/app

volumes:
  jenkins_home:
